version: "3.9"

services:
  # Contenedor principal con Jupyter, Spark y entorno visual
  workspace:
    build: .
    container_name: bigdata_workspace

    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser

    ports:
      - "8888:8888"   # Jupyter
      - "4040:4040"   # Spark UI
      - "5900:5900"   # VNC
      - "6080:6080"   # noVNC

    volumes:
      - .:/home/jovyan/work

    environment:
      - JUPYTER_TOKEN=
      - JUPYTER_PASSWORD=
      - JUPYTER_ALLOW_INSECURE_WRITES=true
      - DISPLAY=:99

    shm_size: "2gb"

    dns:
      - 8.8.8.8   # Arregla problemas de conexión a internet

  # Base de datos MongoDB
  database:
    image: mongo:latest
    container_name: bigdata_mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  # Interfaz web para MongoDB (mongo-express)
  admin-db:
    image: mongo-express:latest
    container_name: bigdata_ui
    restart: always

    ports:
      - "8081:8081"

    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://database:27017/

    depends_on:
      - database

volumes:
  mongo_data: