services:
  # Entorno con interfaz gráfica (VNC) + Spark + Python
  workspace:
    build: .
    container_name: bigdata_workspace
    ports:
      - "8888:8888"   # Jupyter
      - "4040:4040"   # Spark UI
      - "6080:6080"   # VNC (CLAVE semana 6)
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=
      - JUPYTER_PASSWORD=""
      - JUPYTER_ALLOW_INSECURE_WRITES=true

  # MongoDB
  database:
    image: mongo:latest
    container_name: bigdata_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Mongo Express
  admin-db:
    image: mongo-express
    container_name: bigdata_mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=database

volumes:
  mongo_data: